/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package cpuscheduling;

public class App {
  public String getGreeting() {
    return "Hello World!";
  }

  public static void main(String[] args) {
    try {
      System.out.println(args[0]);
    } catch (ArrayIndexOutOfBoundsException e) {
      System.out.println("File not provided");
    }
  }
}
