# Publish the jar file of this project

name: Publish JAR

on:
  release:
    types: [released]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@4
      - uses: actions/setup-java@v3
        with:
          distributions: temurin
          java-version: 11

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Gradle Assemble
        run: ./gradlew assemble

      - name: Publish Jar
        uses: actions/upload-artifacts@v3
        with:
          path: app/build/libs/*.jar
